{{- $chartName := include "exporter-cleanup.name" . -}}
{{- $tracingUrl := include "exporter-cleanup.tracingUrl" . -}}
{{- $metricsUrl := include "exporter-cleanup.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  LOG_LEVEL: {{ quote .Values.env.logLevel }}
  LOG_PRETTY_PRINT_ENABLED: {{ quote .Values.env.logPrettyPrintEnabled }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  HTTP_RETRY_ATTEMPTS: {{ quote .Values.env.httpRetry.attempts }}
  HTTP_RETRY_DELAY: {{ quote .Values.env.httpRetry.delay }}
  HTTP_RETRY_RESET_TIMEOUT: {{ quote .Values.env.httpRetry.delay }}
  JOB_MANAGER_URL: {{ quote .Values.env.jobManager.url }}
  WORKER_TYPES_TILES_JOB_TYPE: {{ quote .Values.env.workerTypes.tiles.jobType }}
  WORKER_TYPES_TILES_TASK_TYPE: {{ quote .Values.env.workerTypes.tiles.taskType }}
  STORAGE_PROVIDER: {{ quote .Values.env.storageProvider }}
  FS_SUB_PATH: {{ quote .Values.env.fs.subPath }}
  S3_API_VERSION: {{ quote .Values.env.s3.apiVersion }}
  S3_ENDPOINT: {{ quote .Values.env.s3.endpointUrl }}
  S3_SSL_ENABLED: {{ quote .Values.env.s3.sslEnabled }}
  S3_MAX_RETRIES: {{ quote .Values.env.s3.maxRetries }}
  S3_BUCKET: {{ quote .Values.env.s3.bucket }}
  S3_PREFIX: {{ quote .Values.env.s3.prefix }}
{{- end }}
