{{- $chartName := include "exporter-cleanup.name" . -}}
{{- $tracingUrl := include "exporter-cleanup.tracingUrl" . -}}
{{- $metricsUrl := include "exporter-cleanup.metricsUrl" . -}}
{{- $configmapName := include "configmap.fullname" . }}
{{- $s3 := (include "common.s3.merged" .) | fromYaml }}
{{- $serviceUrls := (include "common.serviceUrls.merged" .) | fromYaml }}
{{- $jobManagement := (include "common.jobManagement.merged" .) | fromYaml }}
{{- $storage := (include "common.storage.merged" .) | fromYaml }}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
data:
  LOG_LEVEL: {{ quote .Values.env.logLevel }}
  LOG_PRETTY_PRINT_ENABLED: {{ quote .Values.env.logPrettyPrintEnabled }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  HTTP_RETRY_ATTEMPTS: {{ quote .Values.env.httpRetry.attempts }}
  HTTP_RETRY_DELAY: {{ quote .Values.env.httpRetry.delay }}
  HTTP_RETRY_RESET_TIMEOUT: {{ quote .Values.env.httpRetry.delay }}
  JOB_MANAGER_URL: {{ $serviceUrls.jobManager }}
  WORKER_TYPES_TILES_JOB_TYPE: {{ $jobManagement.exporter.jobType | quote }}
  WORKER_TYPES_TILES_TASK_TYPE: {{ $jobManagement.exporter.taskTilesType | quote }}
  STORAGE_PROVIDER: {{ $storage.gpkgProvider | quote  }}
  S3_API_VERSION: {{ .Values.env.s3.apiVersion | quote  }}
  S3_ENDPOINT: {{ $s3.endpointUrl | quote  }}
  S3_SSL_ENABLED: {{ $s3.sslEnabled | quote }}
  S3_MAX_RETRIES: {{ quote .Values.env.s3.maxRetries }}
  S3_BUCKET: {{ $s3.tilesBucket | quote  }}
  S3_PREFIX: {{ quote .Values.env.s3.prefix }}
  BATCH_SIZE: {{ quote .Values.env.s3.batchSize }}
{{- end }}
