{{- $releaseName := .Release.Name -}}
{{- $chartName := include "exporter-cleanup.name" . -}}
{{- $cloudProviderFlavor := include "exporter-cleanup.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "exporter-cleanup.cloudProviderDockerRegistryUrl" . -}}
{{- $imageTag := include "ts-server-boilerplate.tag" . -}}
{{- if .Values.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "exporter-cleanup.environment" . }}
    release: {{ $releaseName }}
    {{- include "exporter-cleanup.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cron.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cron.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.cron.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.cloudProvider.imagePullSecretName }}
          imagePullSecrets:
            - name: {{ .Values.cloudProvider.imagePullSecretName | quote }}
          {{- end }}
          restartPolicy: {{ .Values.cron.restartPolicy }}
          {{- if .Values.rasterCommon.storage.fs.internalPvc.enabled }}
          volumes:
            - name: packages-volume
              persistentVolumeClaim:
                claimName: {{ .Values.rasterCommon.storage.fs.internalPvc.name }} 
          {{- end }}
          containers:
            - name: {{ $releaseName }}-{{ $chartName }}-deployment
              {{- with .Values.image }}
              image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $imageTag }}
              {{- end }}
              envFrom:
                - configMapRef:
                    name: {{ $releaseName }}-{{ $chartName }}-configmap
              env:
                {{- if .Values.rasterCommon.storage.fs.internalPvc.enabled }}
                - name: FS_MOUNT_DIR
                  value: /packages
                - name: FS_SUB_PATH
                  value: {{ .Values.rasterCommon.storage.fs.internalPvc.gpkgSubPath }}
                {{- end }}
                {{- if eq (upper .Values.rasterCommon.storage.gpkgProvider) "S3" }}
                - name: S3_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.rasterCommon.storage.s3.secretName }}
                      key: accessKeyId
                - name: S3_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.rasterCommon.storage.s3.secretName }}
                      key: accessKeyId
                {{- end }}
              {{- if .Values.rasterCommon.storage.fs.internalPvc.enabled }}
              volumeMounts:
                - name: packages-volume
                  mountPath: /packages
                  subPath: {{ .Values.rasterCommon.storage.fs.internalPvc.gpkgSubPath }}
              {{- end }}
              {{- if .Values.resources.enabled }}
              resources:
                {{- toYaml .Values.resources.value | nindent 16 }}
              {{- end }}
{{- end -}}
