{{- if and .Values.s3Secret.enabled .Values.s3Secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.s3Secret.name }}
type: Opaque
stringData:
  accessKeyId: {{ .Values.s3Secret.accessKeyId | quote }}
  secretAccessKey: {{ .Values.s3Secret.secretAccessKey | quote }}
{{- end }}
