{{- if .Values.s3LocalSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rasterCommon.storage.s3.secretName | quote }}
type: Opaque
stringData:
  accessKeyId: {{ .Values.s3LocalSecret.accessKeyId | quote }}
  secretAccessKey: {{ .Values.s3LocalSecret.secretAccessKey | quote }}
{{- end }}
