global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}
  serviceUrls:
    jobManager: ""
  jobManagement:
    exporter:
      jobType: ""
      taskTilesType: ""
  storage:
    gpkgProvider: ""
    fs:
      internalPvc:
        enabled: false
        name: ""
        gpkgSubPath: ""
    s3:
      endpointUrl: ""
      tilesBucket: ""
      sslEnabled: false
      secretName: ""

enabled: true
environment: development

cloudProvider:
  dockerRegistryUrl: my-registry-url.io
  imagePullSecretName: 'my-registry-secret'
  flavor: openshift

image:
  repository: exporter-cleanup
  tag: 'latest'

cron:
  schedule:  '0 0 * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  restartPolicy: OnFailure

serviceUrls:
  jobManager: ""
jobManagement:
  exporter:
    jobType: ""
    taskTilesType: ""
storage:
  gpkgProvider: ""
  fs:
    internalPvc:
      enabled: false
      name: ""
      gpkgSubPath: ""
  s3:
    endpointUrl: ""
    tilesBucket: ""
    sslEnabled: false
    secretName: ""

env:
  logLevel: warn
  logPrettyPrintEnabled: false
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
  httpRetry:
    attempts: 3
    delay: exponential
    shouldResetTimeout: true
  s3:
    maxRetries: 3
    prefix: ""
    batchSize: 100
    apiVersion: 2006-03-01

resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

s3LocalSecret:
  create: false #use for stand alone testing, global s3 secret name should be provided for full deployment
  accessKeyId: "" #use for stand alone testing, global s3 secret name should be provided for full deployment
  secretAccessKey: "" #use for stand alone testing, global s3 secret name should be provided for full deployment

